[versions]
agp = "8.8.2"
kotlin = "2.1.10"
jna = "5.16.0"

[libraries]
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

